version: '3.8'

services:
  python-script:
    build: .
    depends_on:
      logstash:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - elk-kafka-network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - elk-kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9092:9092"
    networks:
      - elk-kafka-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
#      - xpack.security.enabled=true
#      - ELASTIC_PASSWORD=salam
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9200:9200"
    networks:
      - elk-kafka-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9
    depends_on:
      elasticsearch:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk-kafka-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9600/_node/stats" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    networks:
      - elk-kafka-network

networks:
  elk-kafka-network:
    driver: bridge
