version: '3.8'

services:
  python-script:
    build: .
    depends_on:
      - kafka
    networks:
      - elk-kafka-network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - elk-kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - elk-kafka-network

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
#    environment:
#      - discovery.type=single-node
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#    ports:
#      - "9200:9200"
#    networks:
#      - elk-kafka-network
#    depends_on:
#      - kafka
#
#  logstash:
#    image: docker.elastic.co/logstash/logstash:8.5.0
#    depends_on:
#      - elasticsearch
#      - kafka
#    volumes:
#      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#    networks:
#      - elk-kafka-network
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.5.0
#    depends_on:
#      - elasticsearch
#    ports:
#      - "5601:5601"
#    networks:
#      - elk-kafka-network

networks:
  elk-kafka-network:
    driver: bridge
